lsi: false
auto: false
permalink: perma/:year/:month/:day/:title
tag_dir: tag
tag_title_prefix: "Tags &raquo; "
baseurl:  file:///Users/ojilles/jilles.net/_site
markdown: rdiscount
exclude: Rakefile, README.md

# Used by my site (e.g. non jekyll specfic stuff)
title_append: " | Jilles.net"
